site_name: BYU CCE Drone Measurements
site_url: https://byu-cce_drone_measurements.readthedocs.io/en/latest/
site_description: Course materials for the CCE class at BYU
site_author: Instructors and TAs of the CCE class at BYU
repo_url: https://github.com/gus-p-williams/byu-cce-drone_measurements/
#favicon: 'images/favicon.ico'
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - js/mathjax-config.js
extra_css:
  - css/custom.css
markdown_extensions:
    - attr_list
    - sane_lists
    - md_in_html
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.tasklist:
        custom_checkbox: false
        clickable_checkbox: true
    - pymdownx.emoji:

theme:
  name: readthedocs
  logo: images/class_logo.png

nav:
  - Home: index.md
  - Flight Checklist:
      - Pre-Flight Checklist:
          - General Checklist: flight_check_list/pre_flight/pre_general.md
      - Post-Flight Checklist:
          - General Checklist: flight_check_list/post_flight/post_general.md
  - Week 1 - Introduction:
      - Overview: week_01/class_overview.md
      - Fly DJI Mini Resources: week_01/DJI_Mini_Resources.md
  - Week 2 - Software:
      - Bentley iTwin: week_02/bentley_itwin.md
      - QGIS Measurements: week_02/qgis_measurements.md
  - Week 3 - Measurements:
      - Measurements Lab: week_03/lab_measurements.md
      - Metadata: week_03/metadata.md
  - Week 4 - Test Prep:
      - Part 1: week_04/Test_Prep_pt1.md
      - Part 2: week_04/Test_Prep_pt2.md
